/*START DATABASE*/

/*Create tablespaces*/
create tablespace gofar_travel datafile ',tempDataFile01.dbf' size 500m,'tempDataFile02.dbf' size 300m,'tempDataFile03.dbf' size 224m
autoextend on maxsize 1024m
extent management local
segment space management auto
online;

create tablespace test_purposes datafile ',tempDataFile04.dbf' size 500m
autoextend on maxsize 500m
extent management local
segment space management auto
online;

create tablespace test_purposes datafile ',tempDataFile04.dbf' size 500m
autoextend on maxsize 500m
extent management local
segment space management auto
online;

create tablespace Undo datafile ',tempDataFile05.dbf' size 5m
autoextend on maxsize 5m
extent management local
segment space management auto
online;



SELECT TABLESPACE_NAME "TABLESPACE",
   INITIAL_EXTENT "INITIAL_EXT",
   NEXT_EXTENT "NEXT_EXT",
   MIN_EXTENTS "MIN_EXT",
   MAX_EXTENTS "MAX_EXT",
   PCT_INCREASE
   FROM DBA_TABLESPACES; 
   
SELECT * FROM USER_TABLESPACES;

/*USER DBA and assign it to the tablespace called "gofar_travel"*/
CREATE USER DBA_USER 
IDENTIFIED BY dba_user
DEFAULT TABLESPACE gofar_travel 
QUOTA UNLIMITED  ON gofar_travel;

/*Assign dba role and permissions to connect to the user just created*/
GRANT DBA TO DBA_USER;
GRANT CONNECT TO DBA_USER;

/*Profiles*/
CREATE PROFILE manager LIMIT
PASSWORD_LIFE_TIME 40
SESSIONS_PER_USER 1
IDLE_TIME 15
FAILED_LOGIN_ATTEMPTS 4;

CREATE PROFILE finance LIMIT
PASSWORD_LIFE_TIME 15
SESSIONS_PER_USER 1
IDLE_TIME 3
FAILED_LOGIN_ATTEMPTS 2;

CREATE PROFILE development LIMIT
PASSWORD_LIFE_TIME 100
SESSIONS_PER_USER 2
IDLE_TIME 30;

/*Users*/
CREATE USER user1 
IDENTIFIED BY user123
DEFAULT TABLESPACE gofar_travel 
profile manager;

GRANT CONNECT TO user1;

CREATE USER user2 
IDENTIFIED BY user2
DEFAULT TABLESPACE gofar_travel 
profile finance;

GRANT CONNECT TO user2;

CREATE USER user3 
IDENTIFIED BY user3
DEFAULT TABLESPACE gofar_travel 
profile development;

GRANT CONNECT TO user3;

CREATE USER user4 
IDENTIFIED BY user4
DEFAULT TABLESPACE gofar_travel 
profile development;

GRANT CONNECT TO user4;

/*Lock the users associate with profiles: manager and finance*/
ALTER USER user1 ACCOUNT LOCK;
ALTER USER user2 ACCOUNT LOCK;

/*DROP TABLESPACE test_purposes*/
DROP TABLESPACE test_purposes
   INCLUDING CONTENTS AND DATAFILES;
   

/*Vehicles Sequences*/
CREATE SEQUENCE VEHICLES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

/*Accesories Sequences*/
CREATE SEQUENCE ACCESORIES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

/*CUSTOMER Sequences*/
CREATE SEQUENCE CUSTOMER_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

/*INVOICE Sequences*/
CREATE SEQUENCE INVOICE_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

/*INVOCE_DETAIL Sequences*/
CREATE SEQUENCE INVOICE_DETAIL_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

/*SALES_PERSON Sequences*/
CREATE SEQUENCE SALES_PERSON_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

/*CREATE TABLES*/
CREATE TABLE VEHICLES (
  id number PRIMARY KEY,
  status varchar2(36) NOT NULL,
  vin varchar2(255),
  name varchar2(255) default NULL,
  model varchar2(11) default NULL,
  year varchar2(255),
  name_manufacturer varchar2(255),
  cost NUMBER(10,2)  
);

CREATE TABLE ACCESORIES (
  ID number primary key,
  CODE varchar2(255),
  DESCRIPTION varchar(255),
  COST NUMBER(10,2),
  SELLING_PRICE NUMBER(10,2)  
) ;

CREATE TABLE CUSTOMER(
  ID number primary key,
  NAME varchar2(255),
  ADDRESS VARCHAR2(255) default NULL,
  PHONE varchar2(100) default NULL
) ;

CREATE TABLE SALES_PERSON(
  ID number primary key,
  NAME varchar2(255)
) ;

CREATE TABLE INVOICE(
ID NUMBER PRIMARY KEY,
CUSTOMER_ID NUMBER,
VEHICLE_ID NUMBER,
FINAL_PRICE NUMBER(10,2),
PLUS NUMBER(10,2),
TAXES NUMBER(10,2),
LICENSE_FEES NUMBER(10,2),
SALES_PERSON_ID NUMBER
);

CREATE TABLE INVOICE_DETAIL(
ID NUMBER PRIMARY KEY,
INVOICE_ID NUMBER,
ACCESORIES_ID NUMBER
);

    
/*FOREIGN KEYS*/
ALTER TABLE INVOICE_DETAIL ADD CONSTRAINT FK_INVOICE
      FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (ID);
      
ALTER TABLE INVOICE_DETAIL ADD CONSTRAINT FK_ACCESORIES
      FOREIGN KEY (ACCESORIES_ID) REFERENCES ACCESORIES (ID);
      
ALTER TABLE INVOICE ADD CONSTRAINT FK_CUSTOMER
      FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID);

ALTER TABLE INVOICE ADD CONSTRAINT FK_VEHICLE
      FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLES (ID);
      
ALTER TABLE INVOICE ADD CONSTRAINT FK_SALES_PERSON
      FOREIGN KEY (SALES_PERSON_ID) REFERENCES SALES_PERSON (ID);

/*INSERT SALES_PERSON*/
INSERT INTO SALES_PERSON (ID,NAME) VALUES (SALES_PERSON_SEQ.NEXTVAL,'Brenden');
INSERT INTO SALES_PERSON (ID,NAME) VALUES (SALES_PERSON_SEQ.NEXTVAL,'Kimberley');
INSERT INTO SALES_PERSON (ID,NAME) VALUES (SALES_PERSON_SEQ.NEXTVAL,'Leila');
INSERT INTO SALES_PERSON (ID,NAME) VALUES (SALES_PERSON_SEQ.NEXTVAL,'Desirae');
INSERT INTO SALES_PERSON (ID,NAME) VALUES (SALES_PERSON_SEQ.NEXTVAL,'Callie');
INSERT INTO SALES_PERSON (ID,NAME) VALUES (SALES_PERSON_SEQ.NEXTVAL,'Raphael');

/*INSERT CUSTOMER*/
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Cody','Ap #730-7523 Euismod Rd.','1-809-860-5549');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Rhonda','Ap #275-8514 Consectetuer Av.','1-524-963-0431');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Armando','208-7117 Proin Rd.','1-837-587-6539');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Regina','579-9578 Aliquam Rd.','1-153-896-6594');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Tate','Ap #784-5647 Sed Rd.','1-299-940-9526');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Orson','Ap #192-1757 In Road','1-272-611-8059');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Chava','P.O. Box 643, 2485 Duis Rd.','1-452-493-5834');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Jessica','P.O. Box 105, 4328 Malesuada Ave','1-384-690-5912');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Lev','Ap #748-6966 Faucibus. Rd.','1-976-646-5941');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Ulla','161-4415 Orci Avenue','1-183-642-8158');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Rebecca','P.O. Box 566, 1017 Nulla Rd.','1-184-462-9304');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Anjolie','P.O. Box 489, 4390 Augue, Ave','1-157-881-9091');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Kaye','P.O. Box 361, 9112 Eu Rd.','1-103-886-5222');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'James','P.O. Box 358, 1335 Cras Av.','1-767-406-3600');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Kevyn','9152 Sem, St.','1-731-177-0243');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Bethany','3135 Enim Avenue','1-145-848-3990');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Malachi','833-3797 Neque Ave','1-757-173-2061');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Asher','4790 Adipiscing Rd.','1-998-366-7672');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Eve','3204 Egestas. Av.','1-479-719-4357');
INSERT INTO CUSTOMER (ID,NAME,ADDRESS,PHONE) VALUES (CUSTOMER_SEQ.NEXTVAL,'Destiny','P.O. Box 561, 9434 Aliquam Road','1-723-101-1898');

/*Insert Accesories*/
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'78832','ac nulla. In',599756.00,952484.00);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'66524','pede. Cras vulputate velit',878284,479920);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'92482','Duis a mi fringilla mi',544363,606819);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'47288','est, mollis non, cursus',681473,974235);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'93496','ipsum. Curabitur consequat,',508673,241688);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'99436','aliquam',812183,780548);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'93352','dui',114001,757777);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'31739','sem, vitae',222152,768577);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'64676','lorem',567792,947847);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'74683','Donec feugiat metus sit',513412,384869);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'29394','sit',731154,415226);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'24903','suscipit nonummy. Fusce fermentum fermentum',891906,790378);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'01684','Nam',753994,956794);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'50874','feugiat. Lorem ipsum dolor',262027,781689);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'76072','nulla.',736712,562988);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'16124','justo faucibus lectus, a sollicitudin',928185,936563);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'62063','montes, nascetur ridiculus mus.',717550,414176);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'08902','varius. Nam porttitor scelerisque neque.',736672,797632);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'40164','eget',873219,431692);
INSERT INTO ACCESORIES (ID,CODE,DESCRIPTION,COST,SELLING_PRICE) VALUES (ACCESORIES_SEQ.NEXTVAL,'95288','orci lobortis augue',542256,234616);

